Add Support for l3 Addresses on trunk interfaces
bisdn/basebox pull request #270
Opened 2020-10-20 14:16 UTC by rubensfig

## Description

## Motivation and Context

## How Has This Been Tested?

2020-10-20 14:32 UTC, KanjiMonster commented on src/of-dpa/controller.cc
> +    }
maybe something like this has a bit less code reuse:
```
   auto group_id;
  // TODO unfiltered interface
  if (nbi::get_port_type(port) == nbi::port_type_lag)
    group_id = fm_driver.group_id_l2_trunk_interface(port, vid);
  else
    group_id = fm_driver.group_id_l2_interface(port, vid);

  dpt.send_group_mod_message(
        rofl::cauxid(0),
        fm_driver.enable_group_l3_unicast(
        dpt.get_version(), _egress_interface_id, src_mac, dst_mac,
        group_id, false));
```

2020-10-30 09:59 UTC, KanjiMonster requested changes
Please add explanation for your changes, and fix the mentioned issues.

2020-10-30 09:59 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +      rv = vlan->add_vlan(_link.get(), vid, tagged, vrf_id);
You never set `vrf_id` to anything but 0, so just pass 0 here.

2020-10-30 09:59 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +  return rv;
This will break for `!HAVE_RTNL_LINK_BOND_GET_MODE`, since then `rv` is undefined. And even if `HAVE_RTNL_LINK_BOND_GET_MODE`  then `rv` is never set, so you return an undefined value. But this doesn't matter, since you never check the return value.

So either actually set `rv` and check it at the call locations, or just let this return `void`.

2020-10-30 09:59 UTC, KanjiMonster commented on src/netlink/nl_bridge.cc
> +              }
unrelated whitespace change

2020-10-30 09:59 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +      bond->configure_l3_address(new_link);
why do you need this? What happens if ip addresses get removed?

2020-10-30 09:59 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +      bond->configure_l3_address(new_link);
Why do you need this?

2020-10-30 09:59 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +  auto bond = nl->get_link_by_ifindex(rtnl_link_get_master(link));
This could do with some error checking to make sure you don't pass on error values.

2020-10-30 09:59 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
>        bond->remove_lag_member(old_link);
If you add the ip addresses on enslave you should also remove them on deslave.

2020-10-30 09:59 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +      bond->configure_l3_address(new_link);
Also maybe it would make more sense to move the configure_l3_address call being done within `nl_bond::{add,update,remove}_lag_member`, since this is part of the bond code?

2020-10-30 09:59 UTC, KanjiMonster commented on src/of-dpa/controller.cc
> +    }
The call in both branches is now the same, you can drop the if else.

2020-10-30 09:59 UTC, KanjiMonster commented on src/of-dpa/controller.cc
> +    }
The call in both branches is now the same, you can drop the if else.

2020-10-30 14:46 UTC, rubensfig commented on src/netlink/cnetlink.cc
>        bond->remove_lag_member(old_link);
Not necessarily. Its a weird workflow, but a port can be enslaved - removed and another port enslaved again, and we would want to maintain the address on the bond.

2020-10-30 14:58 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
>        bond->remove_lag_member(old_link);
but old_link and new_link will be both the same port; if they are different you would get a LT_BOND_SLAVE => LT_TUN for the one port and LT_TUN => LT_BOND_SLAVE for the other one.

2020-10-30 14:59 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
>        bond->remove_lag_member(old_link);
But the address you took over from above were the addresses that are configured on the bond slave (AFAIU), if you remove the bond slave the addresses should not be configured on the bond anymore.

2020-11-02 10:18 UTC, rubensfig commented on src/netlink/cnetlink.cc
>        bond->remove_lag_member(old_link);
Ah, no. I was not configuring any addresses on the bond slave, since that is not a valid configuration.

What I was doing with this trigger, was checking on port enslavement, start a lookup for addresses on the bond interface, and if something was not configured then we write the address to the ASIC.

2020-11-10 13:20 UTC, KanjiMonster requested changes

2020-11-10 13:20 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +  remove_l3_address(bond);
what happens if I do

```
ip link add name bond1 type bond
ip link address add 10.0.01/24 dev bond1
ip link set port7 master bond1
ip link set port8 master bond1
ip link set port7 nomaster
```
Won't this remove the addresses in that case despite the bond still having members?

2020-11-10 13:20 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> -      rv = add_l3_termination(mem, vid, mac, AF_INET);
Why do you remove this part?

2020-11-10 13:20 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +                 << OBJ_CAST(link);
Maybe also print the address itself?

2020-11-10 13:20 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +    VLOG(1) << __FUNCTION__ << ": BOND configuring slaves";
This log line does not contain any useful information, you should also print the bond you are configuring slaves for

2020-11-10 13:20 UTC, KanjiMonster commented on src/netlink/nl_l3.h
> +  int get_l3_addr(struct rtnl_link *link, std::deque<rtnl_addr *> addresses);
addr -> addrs? (since you are returning multiple

2020-11-10 13:20 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +  add_l3_address(bond);
Shouldn't you only do this if you called `::add_lag`?

2020-11-10 13:20 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +      rv = vlan->add_vlan(_link.get(), vid, tagged, 0);
Actually 0 is the default passed when omitting the argument, so you can just drop it
```suggestion
      rv = vlan->add_vlan(_link.get(), vid, tagged);
```

2020-11-11 11:05 UTC, rubensfig commented on src/netlink/nl_l3.cc
> -      rv = add_l3_termination(mem, vid, mac, AF_INET);
We dont need to add the bond_slave termination MACs anymore, there is the bond interface TMAC entry.

2020-11-12 13:52 UTC, KanjiMonster requested changes

2020-11-12 13:52 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +      LOG(ERROR) << __FUNCTION__ << ":failed to add l3 address " << i << " to "
Does this work without OBJ_CAST'ing the address (i)?

2020-11-12 13:52 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +    LOG(ERROR) << __FUNCTION__ << ": unsupported family ";
please print the address and family here so we know what isn't supported (and maybe deduce where it came from)

2020-11-12 13:52 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +      LOG(ERROR) << __FUNCTION__ << ": failed to get master " << master;
did you intend to print `master_id` or `new_link` here? `master` can only be a nullptr at this point.

2020-11-12 13:52 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +      LOG(ERROR) << __FUNCTION__ << ":failed to add l3 address to "
```suggestion
      LOG(ERROR) << __FUNCTION__ << ":failed to remove l3 address from "
```

And maybe print the address?

2020-11-12 13:52 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +  }
1. This whole block should be in the `if (!is_loopback && !nl->is_bridge_interface())` branch.
2. Don't you need to add a similar block to `nl_l3::del_l3_addr` to remove it?
3. bond interfaces should probably be handled in add/remove vlan (=> https://github.com/bisdn/basebox/commit/7136fe42f8e6fe6795e4e22f77572092d4c87f7a )

2020-11-12 13:52 UTC, KanjiMonster commented on src/of-dpa/controller.cc
> -    // TODO unfiltered interface
This TODO should stay.

2020-11-12 15:51 UTC, KanjiMonster approved these changes

2020-11-30 15:40 UTC, KanjiMonster requested changes

2020-11-30 15:40 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> -    }
Please add an explanation for this change to the commit message.

2020-11-30 15:40 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> -    rv = nl->unset_bridge_port_vlan_tpid(br_link);
Why did you drop this?

2020-11-30 15:40 UTC, KanjiMonster commented on src/netlink/nl_bond.cc
> +  add_l3_address(bond);
And in that case, shouldn't have ::add_lag already taken care of this?

2020-12-03 16:45 UTC, merged