Extend support for VRFs on bonded interfaces
bisdn/basebox pull request #287
Opened 2020-12-10 14:48 UTC by rubensfig

## Description

## Motivation and Context

## How Has This Been Tested?

2020-12-10 16:38 UTC, KanjiMonster requested changes
The first commit has "bonding:" int the title, but has no changes to ::nl_bond. Did you forget to add the changes?

The second commit isn't related to the title of the PR, so should go in a separate PR.

2020-12-10 16:38 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +      vlan->vrf_attach(old_link, new_link);
this looks like a fix that should be a separate commit

2020-12-10 16:38 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +    } // check for unexpected cases
is here a TODO missing, or did you intend to add something here?

2020-12-10 16:38 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +  uint16_t vrf_id = nl->get_vrf_table_id(link);
Any reason for not doing
```
  uint16_t vid = vlan->get_vid(link);
  uint32_t vrf_id = vlan->get_vrf_id(vid, link);
```
?

2020-12-10 16:38 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +    *vrf_id = nl->get_vrf_table_id(link.get());
similar here
```
  *vrf_id = vlan->get_vrf_id(vid, link);
```
?

2020-12-10 16:38 UTC, KanjiMonster commented on src/netlink/nl_vlan.cc
> +    auto id = nl->get_vrf_table_id(link);
Do you really need this? Shouldn't the map have the vrf-id since you add it in attach?

2020-12-10 16:38 UTC, KanjiMonster commented on src/netlink/nl_vlan.cc
> +    remove_ingress_vlan(nl->get_port_id(link.get()), vid, true, 0);
don't you need to re-add the vlan entries again with the vrf set?

2020-12-10 16:38 UTC, KanjiMonster commented on src/netlink/nl_vlan.cc
> +    remove_ingress_vlan(nl->get_port_id(link.get()), vid, true, vlanmap->second);
similar, don't you need to readd them again with vrf unset/0?

2020-12-11 11:37 UTC, rubensfig commented on src/netlink/nl_vlan.cc
> +    remove_ingress_vlan(nl->get_port_id(link.get()), vid, true, 0);
We can just wait that further updates to the interfaces set these entries, so we only need to remove the old state.

2020-12-11 11:42 UTC, KanjiMonster commented on src/netlink/nl_vlan.cc
> +    remove_ingress_vlan(nl->get_port_id(link.get()), vid, true, 0);
Can you please show these updates happening?

e.g. will if e.g. swbridge.10 has a vrf set, will

```
ip link set swbridge.10 nomaster
```
both trigger the removal and whatever is needed to re-add the vlans?

2020-12-14 15:53 UTC, rubensfig commented on src/netlink/nl_vlan.cc
> +    auto id = nl->get_vrf_table_id(link);
We do `uint16_t vrf = get_vrf_id(vid, new_link);` on vrf attach. If the id is not on the map *yet* we need to parse get the table id and add it to the map.

Maybe the function is misnamed, since it does add the vrf id when it does not find it in the map.

2020-12-14 16:01 UTC, KanjiMonster commented on src/netlink/nl_vlan.cc
> +    auto id = nl->get_vrf_table_id(link);
Maybe let vrf_attach call get_vrf_table_id instead of get_vrf_id, and drop the get_vrf_table_id usage from here. Only vrf_attach should extract the vrf_id from the netlink data, everything else should use the map. vrf_attach may even complain if the map already contains a different value for the vlan.

Could it happen that code starts using a vrf (because get_vrf_table_id() returns it) before we handled the attach in vrf_attach? That might lead to weird subtle bugs.

2020-12-16 09:23 UTC, KanjiMonster reviewed
LGTM

2020-12-16 09:23 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +          l3->del_l3_addr(i);
These IP addresses are still assigned to the vlan interface, are they not? Should their entries be just updated to not use reference the vrf anymore instead of removed? And vice versa on the attach path? Might make sense to move this to `vrf_{at,de}tach` then.

2020-12-16 11:20 UTC, rubensfig commented on src/netlink/cnetlink.cc
> +          l3->del_l3_addr(i);
The ip addresses will be readded again shortly after deleting the IP addresses on the link.

```
Dec 16 11:16:41 accton-as4610 baseboxd[1289]: W1216 11:16:41.362574  1298 nl_bridge.cc:776] learn_source_mac: got packet on unconfigured port
Dec 16 11:16:41 accton-as4610 baseboxd[1289]: I1216 11:16:41.962591  1298 cnetlink.cc:1109] link_updated: freed vrf slave interface swbridge.100 ether 4a:0a:73:9d:bc:87 master red <broadcast,multicast,up,running,lowerup> slave-of swbri>
Dec 16 11:16:41 accton-as4610 baseboxd[1289]: I1216 11:16:41.962796  1298 nl_l3.cc:474] get_l3_addrs: searching l3 addresses from interface=swbridge.100 ether 4a:0a:73:9d:bc:87 master red <broadcast,multicast,up,running,lowerup> slave->
...
Dec 16 11:16:41 accton-as4610 baseboxd[1289]: I1216 11:16:41.971890  1298 nl_l3.cc:1260] get_neighbours_of_route: ifindex=62 gw=10.0.100.0/24
Dec 16 11:16:41 accton-as4610 baseboxd[1289]: I1216 11:16:41.971930  1298 nl_l3.cc:1268] get_neighbours_of_route: get neigh of nh_addr=10.0.100.0/24
Dec 16 11:16:41 accton-as4610 baseboxd[1289]: I1216 11:16:41.971967  1298 nl_l3.cc:1535] add_l3_unicast_route: got unresolved nh ifindex=62, nh=10.0.100.0/24
Dec 16 11:16:41 accton-as4610 baseboxd[1289]: I1216 11:16:41.972020  1298 nl_l3.cc:1545] add_l3_unicast_route: got 0 neighbours (1 unresolved next hops)
```

2020-12-16 11:21 UTC, rubensfig commented on src/netlink/cnetlink.cc
> +          l3->del_l3_addr(i);
We do need to process the same in VRF attach, so that this state is avoided. Obtained by running https://github.com/bisdn/basebox/blob/master/examples/routing/VRFs/01-controller and adding first the IP addresses and then configuring the VRF.

```
Table ID 30 (Unicast Routing):   Retrieving all entries. Max entries = 32768, Current entries = 4.
--  etherType = 0x0800 vrf:mask = 0x0000:0x0000 dstIp4 = 10.0.100.0/255.255.255.0 dstIp6 = ::/:: | GoTo = 60 (ACL Policy) outPort = CONTROLLER (Reserved)  | priority = 2 hard_time = 0 idle_time = 0 cookie = 16
--  etherType = 0x0800 vrf:mask = 0x0000:0x0000 dstIp4 = 10.0.200.0/255.255.255.0 dstIp6 = ::/:: | GoTo = 60 (ACL Policy) outPort = CONTROLLER (Reserved)  | priority = 2 hard_time = 0 idle_time = 0 cookie = 19
--  etherType = 0x0800 vrf:mask = 0x3039:0xffff dstIp4 = 10.0.100.0/255.255.255.0 dstIp6 = ::/:: | GoTo = 60 (ACL Policy) outPort = CONTROLLER (Reserved)  | priority = 2 hard_time = 0 idle_time = 0 cookie = 26
--  etherType = 0x0800 vrf:mask = 0x3039:0xffff dstIp4 = 10.0.200.0/255.255.255.0 dstIp6 = ::/:: | GoTo = 60 (ACL Policy) outPort = CONTROLLER (Reserved)  | priority = 2 hard_time = 0 idle_time = 0 cookie = 33
```

2020-12-16 11:23 UTC, rubensfig commented on src/netlink/cnetlink.cc
> +          l3->del_l3_addr(i);
I would also process the IP address not on VRF_{at,de}tach, but on cnetlink, both due to a missing interface to the l3 class, and also because of code workflow.

2020-12-16 13:31 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +          l3->del_l3_addr(i);
Can you please add a comment in the code there why it is okay to delete the addresses and we cannot just update the flows?

2020-12-16 16:29 UTC, KanjiMonster approved these changes
LGTM now

2020-12-16 17:05 UTC, merged