nl_l3: add neigh search and update
bisdn/basebox pull request #301
Opened 2021-03-11 15:04 UTC by rubensfig

## Description
In the case that a certain neighbor is pointing to another egress entry, on address addition we must rewrite the nexthop to point to controller

## Motivation and Context
This use case is seen for example in VRRP.

## How Has This Been Tested?
Ran keepalived test

2021-03-12 14:31 UTC, DFritzsche commented on src/netlink/nl_l3.cc
> +    rv = sw->l3_unicast_route_add(ipv4_dst, mask, 0, false, update, vrf_id);
If 'mask' is only used in the `sw->l3_unicast_route_add` function, I suggest to define mask with 0 and only set it when prefix == 32. This would remove code duplication here and on lines 240-243.

2021-03-12 14:31 UTC, DFritzsche commented on src/netlink/nl_l3.cc
> +  bool update = false;
'update' variable can be defined earlier in the function and used instead of hard-coded 'false' in e.g. `sw->l3_unicast_route_add`

2021-03-16 09:21 UTC, rubensfig commented on src/netlink/nl_l3.cc
> +  bool update = false;
In https://github.com/bisdn/basebox/pull/301/files#diff-0ff22527108b0d3bbb8ff9b1050a2cdd341c2951e766c8e1e72f6a4412af9d25R243, the false value does have to be hardcoded, since we will not handle loopback address updates in this function. In this case, I think hardcoding makes it more explicit that we dont expect an update in this function.

2021-03-16 10:55 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +    rv = sw->l3_unicast_host_add(ipv4_dst, 0, false, update, vrf_id);
What happens if after ~5 minutes the neighbor times out and the kernel sends us a NEIGH_DEL message for this IP?

Won't this trigger a `del_l3_neigh`, which would then call `l3_unicast_host_remove(ipv4_dst)` and break everything?

Also what about IPv6? Or does VRRP only support IPv4?

2021-03-17 07:34 UTC, ideaship commented on src/netlink/nl_l3.cc
> +    rv = sw->l3_unicast_route_add(ipv4_dst, mask, 0, false, update, vrf_id);
How about adding a blank line after this one to make the code more readable?

2021-03-17 07:41 UTC, ideaship commented
I find the lack of comments in this changeset somewhat concerning. Yes, it largely matches the rest of the code, but still, shouldn't the code reader be given a hint on what is going on and why this is needed?

2021-03-17 11:54 UTC, KanjiMonster requested changes

2021-03-17 11:54 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +  // delete l3 unicast group (mac rewrite)
You don't delete the l3 unicast group here, this comment should stay where it was

2021-03-17 11:54 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +  if (family == AF_INET && skip_addr_remove) {
Did you mean `family == AF_INET && !skip_addr_remove`?

2021-03-17 11:54 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +
unnecessary empty line

2021-03-17 11:54 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +  if (family == AF_INET6 && skip_addr_remove) {
```suggestion
  } else if (family == AF_INET6 && skip_addr_remove) {
```

Also did you mean `!skip_addr_remove`?

2021-03-17 11:54 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
>      return -EINVAL;
At this point `link` can't be a nullptr anymore, you have already used it plenty. You need to move this check to top as well.

2021-03-22 11:05 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +              << ": address configured on the interface, skipping";
Which address, which interface? Either add the information, or drop the debug message. Especially since there is nothing else printing that information.

2021-03-24 11:19 UTC, merged