Handle MAC address changes on interfaces
bisdn/basebox pull request #323
Opened 2021-06-25 13:55 UTC by rubensfig

## Description

## Motivation and Context

## How Has This Been Tested?

2021-06-29 09:53 UTC, KanjiMonster requested changes

2021-06-29 09:53 UTC, KanjiMonster commented on src/netlink/nl_interface.cc
> +  if (nl_addr_cmp(rtnl_link_get_addr(old_link), rtnl_link_get_addr(new_link))) {
Why not move this part to `cnetlink::link_updated()` and call ``l3->update_l3_termination(old_link, new_link)`` directly, instead of going through here? Then you can move it outside of the switch case and don't need to explicitly handle the interface type (vlan,tap,bond,bridge,..)

2021-06-29 09:53 UTC, KanjiMonster commented on src/netlink/nl_interface.cc
> +    return 0;
Redundant return call here (and might not be wanted at all).

2021-07-01 08:56 UTC, rubensfig commented on src/netlink/nl_interface.cc
> +  if (nl_addr_cmp(rtnl_link_get_addr(old_link), rtnl_link_get_addr(new_link))) {
This function is already an handler for picking changes on interfaces. I would suggest leaving this here for code readability and making everything concise, instead of spreading the changes all over the place.

2021-07-08 12:40 UTC, KanjiMonster requested changes
I don't see you handling mac address changes on bond interfaces directly.

Also I'm wondering about the worth of the iface class, and if it wouldn't make more sense to do the calls/checks directly in `cnetlink::link_updated()`.

2021-07-08 12:40 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +      });
Any reason you can't just do
```
  for (it : l3_interface_mapping) {
    if (std::get<1>it.first == vid && std::get<2>it.first == old_mac)
      update_l3.emplace(it.first, it.second);
  }
```

2021-07-08 12:43 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +	 VLOG(1) << __FUNCTION__ << ": fdb_res = 0";
This change seems to be unrelated?

2021-07-14 13:53 UTC, KanjiMonster requested changes
Please squash fixes into their appropriate commits, and move any formatting fixes to the start, not in the middle.

Also I still don't see bond interface mac address changes being addressed.

2021-07-14 13:53 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +      port_id = std::get<0>(it.first);
might as well always use the port_id from it.first, it should never be different unless passed on port_id is 0.

2021-07-14 13:53 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +        std::get<2>(it.first) == libnl_lladdr_2_rofl(old_mac))
maybe calculate `libnl_lladdr_2_rofl(old_mac)` once at the beginning instead of doing it at each comparison?

2021-07-14 13:53 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +        port_id, vid, libnl_lladdr_2_rofl(new_mac), std::get<3>(it.first));
likewise with `libnl_lladdr_2_rofl(new_mac)`, calculate it once at the beginning, then reuse it.

2021-07-14 15:10 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +      iface->changed(old_link, new_link);
Is this still needed? You are probably now calling this twice for LT_VLAN I think?

2021-07-15 07:46 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +    update_on_mac_change(old_link, new_link);
Also you might want to make sure that old_link is a device we care about, else you might pick up mac changes on foreign devices (like the management interface) which will all be port_id 0.

2021-07-21 14:57 UTC, KanjiMonster requested changes

2021-07-21 14:57 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +      VLOG(4) << __FUNCTION__ << ": found new refcount=" << i->second;
This output doesn't help much if you don't print for what termination mac entry it is.

2021-07-22 11:53 UTC, KanjiMonster requested changes

2021-07-22 11:53 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +  // their targets by updating the entry and the map.
> they will carry the updated source MAC address.

They don't carry any source mac address at all, which is why we need to look it up, and only see the updated mac address. If they had a source mac address, we wouldn't have that issue.

The messages we get are

1. link Foo changed mac from A to B
2. neigbhor with IP 1 and Mac X was deleted on link Foo

So at step 2, we do not have access to the old mac (foo), and we need to ask someone (nl cache), and they will reply with the current, updated mac.

Btw, you can use paragraphs, they help readability.

2021-07-22 11:53 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +      VLOG(4) << __FUNCTION__ << ": found new refcount=" << i->second
```suggestion
      VLOG(4) << __FUNCTION__ << ": incremented refcount=" << i->second
```

2021-07-22 11:53 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +              << " mac=" << mac << " af=" << af;
```suggestion
      VLOG(4) << __FUNCTION__ << ": decremented refcount=" << i->second
              << " for l3 terminaton for portid=" << port_id << " vid=" << vid
              << " mac=" << mac << " af=" << af;
```

2021-07-22 11:53 UTC, KanjiMonster commented on src/netlink/nl_l3.cc
> +    termination_mac_mapping.emplace(std::move(new_key), refcnt);
why twice?

2021-07-22 13:40 UTC, KanjiMonster requested changes
Please also squash in fixes/suggestions into their respective commits

2021-07-22 13:40 UTC, KanjiMonster commented on src/netlink/cnetlink.cc
> +  // targets by updating the entry and the map.
The deletions come after the source (interface) mac changed, else we wouldn't have the problem.

2021-07-22 15:55 UTC, KanjiMonster approved these changes

2021-07-23 11:10 UTC, merged