add a post exit script to remove KNET interfaces
bisdn/basebox pull request #377
Opened 2022-04-26 08:50 UTC by KanjiMonster

Make sure that all KNET interfaces are removed after baseboxd stopped,
so restarting baseboxd (either intentional or because it crashed) does
not fail due to already existing knet interfaces.

This aligns the behaviour with how it works with the default tap
interfaces, which get removed when baseboxd closes.

The tap interfaces are removed automatically since they are owned by
baseboxd and dropped once baseboxd goes away, but this does not work for
the KNET interfaces, since they are neither owned by baseboxd, nor do
they have any facility to remove them automatically.

The proper way to fix this would be for baseboxd handle sigterm and
gracefully remove them, but the code is currently not equipped well for
that, and will require a larger rework.

As an interim smaller solution, add a python script that directly talks
with the KNET kernel module's ioctl interface to remove all interfaces
and filters, with the exception of the default RxAPI filter, which needs
to be kept.

The IOCTL interface definition is taken from

* https://github.com/Broadcom-Network-Switching-Software/OpenBCM/blob/0b149ddfa3878e65eb217a11dddb999d3e205d03/sdk-6.5.24/include/kcom.h
* https://github.com/Broadcom-Network-Switching-Software/OpenBCM/blob/0b149ddfa3878e65eb217a11dddb999d3e205d03/sdk-6.5.24/systems/linux/kernel/modules/include/bcm-knet.h

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>

## Description

## Motivation and Context

## How Has This Been Tested?

2022-04-26 11:52 UTC, ideaship requested changes

2022-04-26 11:56 UTC, ideaship commented
I'd suggest running pylint against the script. It's up to you which issues raised by it you want to address, but it might give you some ideas for improvement.

2022-04-26 12:08 UTC, KanjiMonster commented
> I'd suggest running pylint against the script. It's up to you which issues raised by it you want to address, but it might give you some ideas for improvement.

Since this is more or less an adaption of c-code, I don't see any of the pylint suggestions as useful, apart from the superfluous  parens after if.

E.g. too few public functions in the Structures? These are c-struct representation, they doesn't have functions. It doesn't make sense to have functions. So this seems to be mostly noise and/or potentially harmful.

2022-04-26 12:51 UTC, ideaship commented
As I said, it's up to you. I know it's mostly noise in this case, but still a good habit to use it.

2022-04-27 09:04 UTC, rubensfig approved these changes

2022-04-27 09:09 UTC, rubensfig commented on scripts/baseboxd-knet-reset.py
> +    fd = os.open("/dev/linux-bcm-knet", os.O_RDWR | os.O_NONBLOCK)
```suggestion
    with  os.open("/dev/linux-bcm-knet", os.O_RDWR | os.O_NONBLOCK) as fd:
       ....
```

2022-04-27 09:13 UTC, rubensfig commented on scripts/baseboxd-knet-reset.py
> +    fcntl.ioctl(fd, 0, io)
Any error/ exception handling for the ioctl call?

2022-04-27 09:22 UTC, ideaship commented on scripts/baseboxd-knet-reset.py
> +    fd = os.open("/dev/linux-bcm-knet", os.O_RDWR | os.O_NONBLOCK)
Actually, if you want to go that way, drop "if os.path.exists("/dev/linux-bcm-knet")". It's not pythonic.

2022-04-27 09:25 UTC, KanjiMonster commented on scripts/baseboxd-knet-reset.py
> +    fd = os.open("/dev/linux-bcm-knet", os.O_RDWR | os.O_NONBLOCK)
So what's the alternative?

2022-04-27 09:37 UTC, KanjiMonster commented on scripts/baseboxd-knet-reset.py
> +    fd = os.open("/dev/linux-bcm-knet", os.O_RDWR | os.O_NONBLOCK)
Then we would need to do a check in the exception handler for it to know whether this is an expected exception or not (if we are running offswitch, then there will be no /dev/linux-bcm-knet, so it failing to open is expected and shouldn't be presented as an error and silently ignored).

Not sure if this is better.

2022-04-27 15:33 UTC, ideaship commented on scripts/baseboxd-knet-reset.py
> +    fd = os.open("/dev/linux-bcm-knet", os.O_RDWR | os.O_NONBLOCK)
```python
try:
    fd = os.open("/dev/linux-bcm-knet", os.O_RDWR | os.O_NONBLOCK)
except FileNotFoundError:
    pass
```
I'm not sure it's _better_, but it is closer to what Python code is supposed to work like.

2022-04-28 08:50 UTC, KanjiMonster commented on scripts/baseboxd-knet-reset.py
> +    fd = os.open("/dev/linux-bcm-knet", os.O_RDWR | os.O_NONBLOCK)
After thinking about this, I think this one is nice since I can then add a comment before the pass that this is fine and isn't an error (which I just did).

2022-04-28 11:19 UTC, merged